package com.tw.progs.HandyEnglish.views.gui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.ProgressBar;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ExamineWords extends VerticalLayout {
    protected Panel pnlGuess;
    protected TextField txtEquiv;
    protected ProgressBar prgProgress;
    protected Button btnOverall;
    protected Button btnGood;
    protected Button btnBad;
    protected TextField txtAnswer;
    protected Button btnCheck;
    protected Button btnNext;
    protected Button btnHint;
    protected Button btnExmpl;
    protected TextArea txaDefn;
    protected TextArea txaExmpl;
    protected Button btnBreak;

    public ExamineWords() {
        Design.read(this);
    }
}
