package com.tw.progs.HandyEnglish.views.gui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class mainPage extends VerticalLayout {
    protected Panel pnlChoose;
    protected Button btnAddWord;
    protected Button btnAddPhrase;
    protected Button btnAddTest;
    protected Button btnAddRule;
    protected Button btnShowDict;
    protected Button btnShowRules;
    protected Button btnExam;
    protected Button btnMultiExam;
    protected Button btnLogout;

    public mainPage() {
        Design.read(this);
    }
}
