package com.tw.progs.HandyEnglish.views.gui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.Panel;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class showRules extends VerticalLayout {
    protected Panel pnlRules;
    protected ListSelect<com.tw.progs.HandyEnglish.db.myBatis.dtos.GramaRule> lstRules;
    protected TextField txtCategory;
    protected TextField txtTitle;
    protected TextArea txtaDefinition;
    protected TextArea txtaExample;

    public showRules() {
        Design.read(this);
    }
}
