package com.tw.progs.HandyEnglish.views.gui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class showDictionary extends VerticalLayout {
    protected Panel pnlDictionary;
    protected ComboBox<com.tw.progs.HandyEnglish.db.myBatis.dtos.Category> cmbCategory;
    protected TextField txtWord;
    protected TextField txtEquiv;
    protected Button btnClear;
    protected Grid<com.tw.progs.HandyEnglish.db.myBatis.dtos.Word> grdData;
    protected TextArea txaDefn;
    protected TextArea txaExmpl;

    public showDictionary() {
        Design.read(this);
    }
}
